name: PR Code Validation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths:
      - 'bcgov-source/app-phocs/main/default**'
      - 'bcgov-source/core/main/default**'
      - 'bcgov-source/app-alr/main/default**'  
      - '.github/workflows/PR_Code_Validation.yml'
      - '!sfdx-project.json'
jobs:
  Code-Validation-Run:
    runs-on: ubuntu-latest
    strategy:
      # By default, if any job in a matrix fails, all other jobs are immediately cancelled. This makes the jobs run to completion instead.
      fail-fast: false
    timeout-minutes: 60
    steps:
      # === Setup. We need to get the code, set up nodejs, and create the results directory. ===
      - uses: actions/checkout@v4
    #  ✅ Set correct Node.js version (required by scanner)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: mkdir smoke-test-results
      
      # === Make three attempts to install sfdx ===
      - name: Install Salesforce CLI (official)
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir ~/sf
          tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1
          echo "$HOME/sf/bin" >> $GITHUB_PATH

      - name: Verify CLI
        run: sf --version

      # === Attempt to install the scanner plugin ===
      - name: Install Scanner Plugin
        run: sf plugins install @salesforce/sfdx-scanner

      # === Log the installed plugins for easier debugging ===
      - name: Log plugins
        run: sf plugins

      # === Static Code Analysis ===
      - name: Run static apexunit validations
        run: sf scanner run --target "${{ vars.RELEASE_PIPELINE_PATH }}" --pmdconfig ruleset/apexunit.xml --format table --engine pmd --normalize-severity --severity-threshold 1

      - name: Run static braces validations
        run: sf scanner run --target "${{ vars.RELEASE_PIPELINE_PATH }}" --format table --pmdconfig ruleset/braces.xml

      - name: Run static complexity validations
        run: sf scanner run --target "${{ vars.RELEASE_PIPELINE_PATH }}" --format table --pmdconfig ruleset/complexity.xml

      # === Attempt to execute static source validations ===
      - name: Run static empty source validations
        id: static_tests_empty
        run: sf scanner run --target "${{ vars.RELEASE_PIPELINE_PATH }}" --format "table" --pmdconfig "ruleset/empty.xml"

      # === Attempt to execute static source validations ===
      - name: Run static complexity source validations
        id: static_tests_metrics
        run: sf scanner run --target "${{ vars.RELEASE_PIPELINE_PATH }}" --format "table" --pmdconfig "ruleset/metrics.xml"

      # === Attempt to execute static source validations ===
      - name: Run static security source validations
        id: static_tests_security
        run: sf scanner run --target "${{ vars.RELEASE_PIPELINE_PATH }}" --format "table" --pmdconfig "ruleset/security.xml"

      # === Attempt to execute static source validations ===
      - name: Run static style source validations
        id: static_tests_style
        run: sf scanner run --target "${{ vars.RELEASE_PIPELINE_PATH }}" --format "table" --pmdconfig "ruleset/style.xml"

      # === Attempt to execute lint source validations ===
      - name: Run lint empty source validations
        id: lint_tests
        run: sf scanner run --engine eslint-lwc --target "${{ vars.RELEASE_PIPELINE_PATH }}"

      # Authenticate CI01 sandbox
      - name: 'Authenticate CI01 Sandbox'
        run: |
            echo "${{ secrets.CI_SFDXAUTHURL }}" > ./authfile
            sf org login sfdx-url -f authfile -a CI01

      - name: Validate Code
        id: run_code_validation
        run: sf project deploy start --source-dir "${{ vars.RELEASE_PIPELINE_PATH }}" --wait 60 --dry-run --test-level RunLocalTests --target-org CI01
RELEASE_PIPELINE_PATH